### ISSUE TITLE
Client sockets won't connect

### ISSUE THREAD

**Issue by Adam13531** [Decatek/learn-node#1]
Hey Decatek. :)

I found the problem you're having. It turns out that you're not specifying the port in your client code:

    var chat_infra = io('/chat_infra');
    var chat_com = io('/chat_com');

The above is essentially saying "connect me to the same host that I'm on for whatever the default port is". The host is "http://localhost", and the default port will be 80. However, you likely start your server with "npm start" or "node app", which defaults to using port 3000.

You can use one of two solutions:

    // Solution 1: manually specify host/port
    var chat_infra = io.connect('http://localhost:3000/chat_infra');
    var chat_com = io.connect('http://localhost:3000/chat_com');

Solution 2: just do `set port=80` (Windows) or `export port=80` (Unix/Linux) before starting your application. Then, make sure to go to just "http://localhost" instead of "http://localhost:3000".

**Comment by Decatek** [comment]
Thank you very much again for looking into this, the documentation on socket.io is not very explicit about this behaviour, but now it's all documented in my personal notes.
I fixed it using the first solution.
